[wallpaper]
    [wallpaper.default]
    path = "/home/devinr/Pictures/Wallpapers/6x standard Until Then OST cover.jpg"

    [wallpaper.last]
    path = "/home/devinr/Pictures/Wallpapers/6x standard Until Then OST cover.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/devinr/Pictures/Wallpapers/raidenKatana.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/devinr/Pictures/Wallpapers/raidenKatana.jpg"

    [wallpaper.monitors.DP-5]
    path = "/home/devinr/Pictures/Wallpapers/6x standard Until Then OST cover.jpg"

    [wallpaper.monitors.DP-6]
    path = "/home/devinr/Pictures/Wallpapers/6x standard Until Then OST cover.jpg"

    [wallpaper.monitors.Unknown-1]
    path = "/home/devinr/Pictures/Wallpapers/untilThen/Mark & Nicole Piano Dinner.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/andiurne/Pictures/Wallpapers/6x standard Until Then OST cover.jpg"

[widget.media]
art_size = 28.0

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.spacer_2]
type = "spacer"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
empty_color = "tertiary"
