keys:
  - &andiurne age1fnnq89dsu0vj2s26pa7yt58jj4ylj69lzwku0zjvk62900m9mu3swwq6a0
  - &enchantedSlate age1l8k24urdc8gx5eks6kajum52s0p6mg5t5zxrg5kswxzftm2jnffsqvvtjm
  - &devinr age1qqmq39d0sxy5gex7dmta8t65qnu08t6n63w2mkr52uwvpns0hvks5srvqv
  - &vc-station age1d94e2gpvyeuscxyz8wnxg29awd57u9w9vsdy2sd3jav0x9t9mpxqhedp97
creation_rules:
  - path_regex: .+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *andiurne
          - *devinr
          - *enchantedSlate
          - *vc-station
