keys:
  - &andiurne age1fnnq89dsu0vj2s26pa7yt58jj4ylj69lzwku0zjvk62900m9mu3swwq6a0
  - &enchantedSlate age1n3kf3hsglrr5lqrwr3s67s07z8r4dfd20ctecxgcfsva7jpvjarq7jk4j8
  - &devinr age1qqmq39d0sxy5gex7dmta8t65qnu08t6n63w2mkr52uwvpns0hvks5srvqv
  - &vc-station age1rgffpespcyjn0d8jglk7km9kfrfhdyev6camd3rck6pn8y47ze4sug23v3
creation_rules:
  - path_regex: .+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *andiurne
          - *devinr
          - *enchantedSlate
          - *vc-station
