theme {
  color_scheme = ~/.config/qt6ct/colors/noctalia.conf
  icon_theme = Papirus-Dark
  style = "Fusion"
  font_fixed = "JetBrainsMono Nerd Font"
  font_fixed_size = 10
  font = "JetBrainsMono Nerd Front"
  font_size = 10
}
