# Noctalia theme for snappy-switcher

[colors]
background = #292414aa
card_bg = #453c21aa
card_selected =  #4c4225ff
text_color = #fbf7e9dd
subtext_color =  #fbf7e9cc
border_color =  #736d5eff
bundle_bg = #6f2510ff
badge_bg =  #d6775caa
badge_text_color = #252218aa
badge_bg_selected = #d6775ccc
badge_text_color_selected = #252218ff