# Noctalia theme for snappy-switcher

[colors]
background = #291d14aa
card_bg = #453021aa
card_selected =  #4c3425ff
text_color = #f5e3d6dd
subtext_color =  #f5e3d6cc
border_color =  #74675fff
bundle_bg = #6f6d10ff
badge_bg =  #d6d35caa
badge_text_color = #251d18aa
badge_bg_selected = #d6d35ccc
badge_text_color_selected = #251d18ff