# Noctalia theme for snappy-switcher

[colors]
background = #191429aa
card_bg = #292145aa
card_selected =  #2d254cff
text_color = #e1ddeedd
subtext_color =  #e1ddeecc
border_color =  #656176ff
bundle_bg = #55106fff
badge_bg =  #b45cd6aa
badge_text_color = #1b1825aa
badge_bg_selected = #b45cd6cc
badge_text_color_selected = #1b1825ff