keys:
  - &andiurne age1fnnq89dsu0vj2s26pa7yt58jj4ylj69lzwku0zjvk62900m9mu3swwq6a0
  - &enchantedSlate age1n3kf3hsglrr5lqrwr3s67s07z8r4dfd20ctecxgcfsva7jpvjarq7jk4j8
  - &enchantedObelisk age1sg2jtu3fya238p7agxrl7w5ezy9sux6m7r6n7gw6yetdxzyltagsn8u078
creation_rules:
  - path_regex: .+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *andiurne
          - *enchantedSlate
          - *enchantedObelisk
