-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/

-- extraLuaFiles
local hm_xdg_config_home = os.getenv("XDG_CONFIG_HOME") or "/home/andiurne/.config"
package.path = hm_xdg_config_home .. "/hypr/?.lua;" .. hm_xdg_config_home .. "/hypr/?/init.lua;" .. package.path
require("autostart")
-- extraConfig
require("aesthetics")
require("input")
require("monitors")
require("autostart")
require("windows")
require("misc")
require("keybinds")

require("noctalia_conf")
require("noctalia").apply_theme()

hl.env("HYPRCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_THEME", "King Halo")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

